### ISSUE TITLE
Change the Start Angle

### ISSUE THREAD

**Issue by cmag0505** [caolsen/CircularSlider#1]
Hi,
first of all thank you for the great Slider. I am brand new to programming, never done anything like it before and still have lots of staff to learn :o)

I would appreciate if you could tell me, how I could change the start Angle of the filled track in the CircleSlider and maybe how I could use the gradient not just for the background circle but for the other one as well.
I tried working it out, but unfortunately so far, no Luck.

Thanks a lot.
Cosima

**Comment by cmag0505** [comment]
Hi,
sorry, it's me again :o)

I did figure my first partially out, so I know now how to change the Start Angle.
But I hit a problem with updating the slider.
See, I would like to use the slider as progress and slider for a Mediaplayer. But when I set a timer on it, say with a timerInterval of a second, than it just keeps repeating the same second, and the fildArc doesn't move.

Maybe you have any thoughts on that?
Thanks a lot.
Cosima

**Comment by caolsen** [comment]
Hey Cosima,

Thanks for the comments. Glad you figured some stuff out.

You can update the start angle by changing the slider's `currentValue`. I did not initially design the slider to be updated programmatically which is why you are running into the issue above; `currentValue` was only for initial setup.

However, I think it makes sense for `currentValue` to be updated and have the changes reflected in the UI. So, I'm classifying this as a bug and implemented a fix. The problem was that `setNeedsDisplay` was not being called after `currentValue` was set. It should work for you now. :+1: 

For the Gradient Slider: I designed it to only be used as a background for the unfilled color with a transparent filled color. I'll consider adding that as a feature in the future or feel free to submit a pull request.

Thanks,
Chris

**Comment by cmag0505** [comment]
Hi,
thank you so much for your quick reply, but I,m still hitting a problem.
Maybe I'm just doing something wrong here, but I'm using the same code as I did with a normal slider.

Here is all the code I use for the slider. With a standard slider it works fine.
Maybe you could have a quick look at it. Maybe I just set the slider up wrong.
Thanks again.

Cosima

@IBAction func valueChanged(slider: CircularSlider) {
    let time: CMTime = CMTimeMakeWithSeconds(Float64(slider.currentValue), 10000)
    player.seekToTime(time, toleranceBefore: kCMTimeZero, toleranceAfter: kCMTimeZero)
  }

  func setUpCircularSlider() {
    let frame = CGRectMake(0, 0, sliderView.frame.width, sliderView.frame.height)
    let circularSlider = CircularSlider(frame: frame)

```
// setup target to watch for value change
circularSlider.addTarget(self, action: Selector("valueChanged:"), forControlEvents: UIControlEvents.ValueChanged)

// setup slider defaults
circularSlider.handleType = .BigCircle
circularSlider.maximumValue = duration
circularSlider.minimumValue = 0
circularSlider.lineWidth = 10

timer = NSTimer.scheduledTimerWithTimeInterval(1.0, target: self, selector: "fire:", userInfo: nil, repeats: true)
// add to view
sliderView.addSubview(circularSlider) 
```

  }
    func fire(timer: NSTimer) {
    self.timeSlider.currentValue = Float(CMTimeGetSeconds(player.currentTime()))
  }

**Comment by caolsen** [comment]
I'm not very familiar with CoreMedia, so I don't know how much help I can be.

If I run a simple timer like this it works for me:

```
func fire(timer: NSTimer) {
    let time = CMTimeMakeWithSeconds(seconds, 10000)
    circularSlider.currentValue = Float(CMTimeGetSeconds(time))
    seconds = seconds + 1
  }
```

Do you have a git repo for your code? I could take a look if that would help.

I noticed in you example above you declare the slider `let circularSlider = CircularSlider(frame: frame)` inside the `setUpCircularSlider()` block. Also, in the `func fire` you are referencing a different slider (timeSlider). Could this be the issue?

Let me know if any of that helps.

-Chris

**Comment by cmag0505** [comment]
Hi Chris,

thanks a lot. 
I don't have a Repo on Github, don't really know, how to get the code on Github. As I said, I'm a total newbie an have plenty to learn.
Anyway, it seems to work now, maybe it was the timescale which was missing. So thanks again.
But just out of curiousity? Where do you get your "seconds" from?

Cosima

**Comment by caolsen** [comment]
Great, I'm glad things are working for you.

My seconds was just a dummy variable that I was incrementing to simulate an actual player.

Good luck with the media player.

-Chris
