### ISSUE TITLE
Can't obtain correct gradient distribution

### ISSUE THREAD

**Issue by Silvia4** [caolsen/CircularSlider#3]
Hi, 
first of all thanks for your library, I like it!
I'm finding some problem in the gradient mode. I've set only half a circle, but the gradient is not going from blue to red correctly, the first color starts after some angle (see in the screenshot above).
<img width="311" alt="termo" src="https://user-images.githubusercontent.com/38463563/41421060-2d65a78e-6ff6-11e8-9015-52111c52eb29.png">

This is my code:

```
        circularSlider.maximumAngle = 220.0
        circularSlider.minimumValue = 0
        circularSlider.maximumValue = 16
        circularSlider.transform = circularSlider.getRotationalTransform()
        circularSlider.lineWidth = 28
        circularSlider.unfilledGradientColors = [UIColor.blue, UIColor.red]
```
Thanks!

**Comment by caolsen** [comment]
So, the gradient feature doesn't work great. It's something on my list to fix, but I haven't gotten around to it. I wrote this all a while ago, so it's not fresh in my memory.

I don't have plans to fix it currently, but if it's something you want to look at feel free to submit a PR.

There are two issues at play here.

1) When the slider arc is less than 360 degrees it gets rotated by the ```getRotationalTransform()``` result. This also rotates the gradient and causes some of what you're seeing.

2) The gradient fills the entire rectangular slider view running left to right and is then masked with the actual slider arc.  This means that a 180 degree or less slider would show a smooth transition, but arcs greater than 180 degrees start to bleed toward the "wrong" color.
See the fairly crude example below.

![photoshop-foreground-background-gradient](https://user-images.githubusercontent.com/3180412/41484987-5f448b5e-70a4-11e8-8402-17f5f4b557cc.jpg)

**Comment by Silvia4** [comment]
Hi, thanks for your reply. I think that in my case the second point would not be a problem, but it's mainly the first one. Do you think that it's possible to rotate only the slider, and later apply the gradient?
